[advisories]
ignore = []

[licenses]
allow = [
    "Apache-2.0",
    "GPL-3.0",
    "GPL-3.0-only",
    "MIT",
    "Unicode-3.0",
]

[bans]
multiple-versions = "warn"
wildcards = "deny"
highlight = "all"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
